export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const FILTER_TODO = 'FILTER_TODO';
export const CHANGE_TODO_STATE_SUCCESS = 'CHANGE_TODO_STATE_SUCCESS';


export const CLEAR_COMPLETED_TODO_SUCCESS = 'CLEAR_COMPLETED_TODO_SUCCESS';
export const COMPLETE_ALL_TODO_SUCCESS = 'COMPLETE_ALL_TODO_SUCCESS';

export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const SET_FAILURE_STATE = 'SET_FAILURE_STATE';

export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export const LOG_OUT = 'LOG_OUT';
export const INIT_TODO_STATE = 'INIT_TODO_STATE';
